### ISSUE TITLE
Counting triggers for each host

### ISSUE THREAD

**Issue by rpereira90** [alexander-nesterov/zabbix_get_events#5]
How would I go about counting triggers for each Host?
Basically I need something like this:
![imagem](https://user-images.githubusercontent.com/28969174/36428610-46ef1e86-1648-11e8-8fef-75248e34de8f.png)

**Comment by 0x12ee705** [comment]
you can do it)))

**Comment by rpereira90** [comment]
it's been hours, honestly I can't figure it out ... I'm not a programmer, and it's the first time I've ever used perl. can you please give me an hint

**Comment by 0x12ee705** [comment]
you need to use Excel formulas, I think so

**Comment by rpereira90** [comment]
I figure it out, using excel formulas!
excel::writer::xlsx is great thanks
